#!/usr/bin/env bash
#
# Writes .env.testing if there is none. The ONE writer of that file: CI's jobs
# (`npm run env:testing`), scripts/e2e-serve.sh and a developer's first
# `npm run test:e2e` all go through here, so a new key is added in one place.
#
# Idempotent — an existing file is left alone, so local edits survive.
# Written for the macOS default bash 3.2.
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env.testing"

if [ -f "$ENV_FILE" ]; then
  exit 0
fi

echo "[env:testing] Generating ${ENV_FILE}" >&2
cat > "$ENV_FILE" <<ENV
# Generated by scripts/ensure-env-testing.sh — safe to edit, regenerated only if deleted.
NODE_ENV=testing
PORT=3000
# The disposable Postgres from docker-compose.test.yml — on 5433 so it can run
# beside the dev one on 5432. Credentials are literals there too.
DATABASE_URL=postgres://postgres:postgres@localhost:5433/app_test
# The frontend Playwright suite serves the built SPA on :4173 and calls this
# API on :3000 — cross-origin, the same shape as a deployed environment.
CORS_ORIGINS=http://localhost:4173
SWAGGER_ENABLED=false
ENV
